ControleCliente.Web/Models/Cliente.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ControleCliente.Web.Models
{
    public class Cliente
    {
        public int ClienteID { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string CNPJ { get; set; }
        public string Logradouro { get; set; }
        public int Numero { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
        public string Municio { get; set; }
        public string Cep { get; set; }

        public int UsuarioID { get; set; }

        [ForeignKey("UsuarioID")]
        public virtual Usuario usuario { get; set; }
    }
}

ControleCliente.Web/Models/Usuario.cs
using System.Collections.Generic;

namespace ControleCliente.Web.Models
{
    public class Usuario
    {
        public int UsuarioID { get; set; }

        public string NomeUsuario { get; set; }

        public string Senha { get; set; }

        public string NomeCompleto { get; set; }

        public string Email { get; set; }

        public string Telefone { get; set; }

        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}

ControleCliente.Web/Controllers/ClienteController.cs
using ControleCliente.Web.Helper;
using ControleCliente.Web.Repository;
using ControleCliente.Web.ViewModel;
using System.Net;
using System.Web.Mvc;

namespace ControleCliente.Web.Controllers
{
    public class ClienteController : Controller
    {
        private ClienteRepository clienteRepository = new ClienteRepository();
        private UsuarioRepository usuarioRepository = new UsuarioRepository();
        // GET: Client
        [Authorize]
        public ActionResult Detalhes(int ClienteID)
        {
            var Cliente = clienteRepository.GetCliente(ClienteID);
            if (Cliente == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(Cliente);
        }

        [Authorize]
        public ActionResult Editar(int ClienteID)
        {
            var Cliente = clienteRepository.GetCliente(ClienteID);
            if (Cliente == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(Cliente);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Editar([Bind(Include = "ClienteID,RazaoSocial,NomeFantasia,CNPJ,Logradouro,Numero,Bairro,Complemento,Municio,Cep,UsuarioID")]ClienteViewModel cliente)
        {
            if (!MyValidator.ValidarCNPJ(cliente.CNPJ))
            {
                ModelState.AddModelError("", "CNPJ Inválido");
                return View(cliente);
            }
            if (clienteRepository.VerificarCNPJExistente(cliente.CNPJ, cliente.ClienteID))
            {
                ModelState.AddModelError("", "CNPJ Inválido");
                return View(cliente);
            }
            if (clienteRepository.UpdateCliente(cliente))
            {
                return RedirectToAction("Index", "Usuario");
            }
            ModelState.AddModelError("", "CNPJ Inválido");
            return View(cliente);
        }

        
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(ClienteViewModel cliente)
        {
            int usuarioID = usuarioRepository.GetUsuarioID(User.Identity.Name);
            cliente.UsuarioID = usuarioID;
            if(!MyValidator.ValidarCNPJ(cliente.CNPJ))
            {
                ModelState.AddModelError("", "CNPJ Inválido");
                return View(cliente);
            }
            if (clienteRepository.AddCliente(cliente))
                return RedirectToAction("Index","Usuario");

            ModelState.AddModelError("", "CNPJ já está em uso");
            return View(cliente);
        }
    }
}

ControleCliente.Web/Controllers/UsuarioController.cs
using System.Linq;
using System.Web.Mvc;
using ControleCliente.Web.ViewModel;
using ControleCliente.Web.Repository;
using System.Net;
using System.Web.Security;
using ControleCliente.Web.Helper;

namespace ControleCliente.Web.Controllers
{

    public class UsuarioController : Controller
    {
        private UsuarioRepository usuarioRepository = new UsuarioRepository();
        private ClienteRepository clienteRepository = new ClienteRepository();

        [Authorize]
        public ActionResult Detalhes()
        {
            UsuarioViewModel usuario = usuarioRepository.GetUsuario(User.Identity.Name);
            if (usuario == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(usuario);
        }

        [Authorize]
        public ActionResult Edit()
        {
            
            UsuarioSignInViewModel user = usuarioRepository.GetUsuarioSignIn(User.Identity.Name);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(user);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "UsuarioID,NomeUsuario,Senha,ConfirmarSenha,NomeCompleto,Email,Telefone")] UsuarioSignInViewModel usuario)
        {
            UsuarioLoginViewModel login = new UsuarioLoginViewModel()
            {
                Login = usuario.NomeUsuario,
                Senha = usuario.ConfirmarSenha
            };
            if(!usuarioRepository.CheckUsuario(login))
            {
                ModelState.AddModelError("", "Senha Invalida.");
                return View(usuario);
            }
            if (usuarioRepository.UpdateUsuario(usuario))
            {
                FormsAuthentication.SignOut();
                FormsAuthentication.SetAuthCookie(usuario.NomeUsuario, false);
                return RedirectToAction("Detalhes");
            }
            ModelState.AddModelError("", "Login já Cadastrado no Sistema.");
            return View(usuario);
        }

        [Authorize]
        [HttpPost]
        public void AlterarSenha(string OldSenha, string NewSenha, string ConfirmNewSenha)
        {
            //string OldSenha,string NewSenha,string ConfirmNewSenha
            usuarioRepository.ChangePassword(User.Identity.Name, OldSenha, NewSenha, ConfirmNewSenha);
            

        }

        [Authorize]
        public ActionResult Index()
        {
            int usuarioID = usuarioRepository.GetUsuarioID(User.Identity.Name);
            var list = clienteRepository.GetClientes(usuarioID);
            return View(list);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Index(string pesquisa)
        {
            int usuarioID = usuarioRepository.GetUsuarioID(User.Identity.Name);
            var list = clienteRepository.GetClientes(usuarioID);
            list = list.Where(x => StringSearch.StartsWith(x.RazaoSocial,pesquisa));
            int size = list.ToList().Count;
            var list2 = list.ToList();
            if (Request.IsAjaxRequest())
                return PartialView("_Clientes", list);

            return View(list);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ExcluirCliente(int id)
        {
            clienteRepository.RemoveCliente(id);
            int Id = usuarioRepository.GetUsuarioID(User.Identity.Name);
            if (Request.IsAjaxRequest())
                return PartialView("_Clientes",clienteRepository.GetClientes(Id));

            return RedirectToAction("Index");
        }
    }
}

ControleCliente.Web/Views/Usuario/Detalhes.cshtml
@model ControleCliente.Web.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Detalhes";
}

<div class="modal-content col-sm-9 mx-auto pb-2 mb-5 mt-5">
  <div class="modal-header">
      <h2 class="mx-auto">Detalhes</h2>
  </div>
      <div class="modal-body">
        <div class="row mb-4">
            <div class="col-sm-3 offset-sm-3 text-center">
                @Html.LabelFor(m => m.NomeUsuario,new { @class= "font-weight-bold" })
                <div class="row border-bottom border-dark">
                    <span class="ml-auto mr-auto">
                        @Html.DisplayFor(m => m.NomeUsuario, new { @class = "" })
                    </span>
                </div>
              
            </div>

            <div class="col-sm-2 offset-sm-1 text-center">
                @Html.LabelFor(m => m.Telefone, new { @class = "font-weight-bold" })
                <div class="row border-bottom border-dark">
                    <span class="ml-auto mr-auto">
                        @Html.DisplayFor(m => m.Telefone, new { @class = "" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-sm-6 offset-sm-3 text-center">
                @Html.LabelFor(m => m.NomeCompleto, new { @class = "font-weight-bold" })
                <div class="row border-bottom border-dark">
                    <span class="ml-auto mr-auto">
                        @Html.DisplayFor(m => m.NomeCompleto, new { @class = "" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-sm-6 offset-sm-3 text-center">
                @Html.LabelFor(m => m.Email, new { @class = "font-weight-bold" })
                <div class="row border-bottom border-dark">
                    <span class="ml-auto mr-auto">
                        @Html.DisplayFor(m => m.Email, new { @class = "" })
                    </span>
                </div>
            </div>
        </div>



    </div>

    <div class="modal-footer">
          <a class="btn btn-secondary" href="@Url.Action("Index","Usuario")">Voltar</a>
        <a id="editModal" class="ml-2 btn btn-success text-white"><i class="fa fa-user-lock mr-1"></i>Alterar Senha</a>
          <a class="ml-2 btn btn-primary text-white" href="@Url.Action("Edit","Usuario")"><i class="fa fa-edit"></i>Editar</a>

    </div>
</div>


<div class="invisivel" id="modal_editar" role="dialog">
    @using (Ajax.BeginForm("AlterarSenha", "Usuario", null, new AjaxOptions { HttpMethod = "POST" }))
    {
        <div class="modal-body">
            <div class="form-group col-md-8">
                @Html.Password("OldSenha", "", new { @class = "form-control", placeholder = "Senha Atual" })
            </div>
            <div class="form-group col-md-8">
                @Html.Password("NewSenha", "", new { @class = "form-control", placeholder = "Nova Senha" })
            </div>
            <div class="form-group col-md-8">
                @Html.Password("ConfirmNewSenha", "", new { @class = "form-control", placeholder = "Confirmar Nova Senha" })
            </div>

            <div class="form-group">
                <a role="button" data-dismiss="modal" class="btn btn-light">Cancelar</a>
                <button type="submit" class="btn btn-secondary"><i class="fa fa-save mr-1"></i>Salvar</button>
            </div>
        </div>

    }
</div>


@section Scripts{

    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).on('click', '#editModal', function () {
                var modal_editar = $('#modal_editar');
                bootbox.dialog({
                    title: 'Alterar Senha',
                    message: modal_editar
                })
                    .on('shown.bs.modal', function () {
                        modal_editar.show(0, function () {
                            $("#OldPassword").focus();
                        });
                    })
                    .on('hidden.bs.modal', function () {
                        $("#OldPassword").val("");
                        $("#NewPassword").val("");
                        $("#CNewPassword").val("");
                        modal_editar.appendTo('body');
                        modal_editar.hide();
                    });

        });
    </script>
}

ControleCliente.Web/Views/Usuario/Edit.cshtml
@model ControleCliente.Web.ViewModel.UsuarioSignInViewModel
@{
    ViewBag.Title = "Edit";
}

<div class="modal-content col-sm-9 mx-auto pb-2 mb-5 mt-5">
    <div class="modal-header">
        <h2 class="mx-auto">Editar</h2>
    </div>

        @using (Html.BeginForm())
        {
            <div class="modal-body">
                @Html.ValidationSummary(true, "", new { @class = "text-red" })
                @Html.HiddenFor(m => m.UsuarioID)
                @Html.HiddenFor(m => m.Senha)
                <div class="row mb-4">
                    <div class="col-sm-3 offset-sm-3 text-center">
                        @Html.LabelFor(m => m.NomeUsuario, new { @class = "font-weight-bold" })
                        <div class="row">
                            @Html.TextBoxFor(m => m.NomeUsuario, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NomeUsuario, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="col-sm-2 offset-sm-1 text-center">
                        @Html.LabelFor(m => m.Telefone, new { @class = "font-weight-bold" })
                        <div class="row">
                            @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Telefone, "", new { @class = "text-danger", id = "Phone" })
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6 offset-sm-3 text-center">
                        @Html.LabelFor(m => m.NomeCompleto, new { @class = "font-weight-bold" })
                        <div class="row">
                            @Html.TextBoxFor(m => m.NomeCompleto, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NomeCompleto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-sm-6 offset-sm-3 text-center">
                        @Html.LabelFor(m => m.Email, new { @class = "font-weight-bold" })
                        <div class="row">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-sm-6 offset-sm-3 text-center">
                        @Html.LabelFor(m => m.ConfirmarSenha, new { @class = "font-weight-bold" })
                        <div class="row">
                            @Html.Password("ConfirmarSenha","", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.ConfirmarSenha, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

    <div class="modal-footer">
        <a class="btn btn-secondary" href="@Url.Action("Detalhes","Usuario")">Voltar</a>
        <button type="submit" class="btn btn-success text-white"><i class="fa fa-save m-1"></i>Salvar</button>
    </div>
        }

          
</div>


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#Phone").mask("(99)9999-9999");
        });
    </script>
}

ControleCliente.Web/Views/Usuario/Index.cshtml
@model IEnumerable<ControleCliente.Web.ViewModel.ClienteViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="col-md-12 my-md-5">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Clientes</h2>
            @using (Ajax.BeginForm("Index","Usuario",new AjaxOptions { HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,UpdateTargetId = "ClientTable"},new { @class="mr-auto ml-auto"}))
            {
                <div class="form-inline">
                    @Html.TextBox("pesquisa", null, new { @placeholder = "Digite o nome", @class = "form-control mr-2" })
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search mr-1"></i>Buscar</button>
                </div>

            }
        </div>
        <div class="modal-body">
            @Html.Partial("_Clientes", Model)
        </div>
        <div class="modal-footer">
            <a href="@Url.Action("Create","Cliente")" class="btn btn-success"><i class="fa fa-plus mr-1"></i>Adicionar</a>
        </div>
    </div>

</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#navSearch").remove();
    </script>
}

ControleCliente.Web/Views/Usuario/_Clientes.cshtml
@model IEnumerable<ControleCliente.Web.ViewModel.ClienteViewModel>
@{
    ViewBag.Title = "Clientes";
}

<table class="table table-hover " id="ClientTable">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Razão Social</th>
            <th scope="col">CNPJ</th>
            <th scope="col">Municipio</th>
            <th scope="col">Logradouro</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        @{int cont = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@cont</th>
                <td>@item.RazaoSocial</td>
                <td>@item.CNPJ</td>
                <td>@item.Municio</td>
                <td>@item.Logradouro</td>
                <td>
                    @Ajax.ActionLink(
                   "Excluir", "ExcluirCliente", "Usuario",new { id = item.ClienteID}
                   ,new AjaxOptions
                   {   HttpMethod = "POST",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "ClientTable"}
                   ,new { @class="btn btn-danger mr-1"} )
                    <a class="btn btn-primary mr-1" href="@Url.Action("Editar","Cliente",new{ ClienteID = item.ClienteID})">
                        <i class="fa fa-edit mr-1"></i>Editar
                    </a>
                </td>

                @{cont = cont + 1; }
            </tr>
        }


    </tbody>
</table>