ControleCliente.Web/Controllers/UsuarioController.cs
using System.Linq;
using System.Web.Mvc;
using ControleCliente.Web.ViewModel;
using ControleCliente.Web.Repository;
using System.Net;
using System.Web.Security;
using ControleCliente.Web.Helper;

namespace ControleCliente.Web.Controllers
{

    public class UsuarioController : Controller
    {
        private UsuarioRepository usuarioRepository = new UsuarioRepository();
        private ClienteRepository clienteRepository = new ClienteRepository();

        [Authorize]
        public ActionResult Detalhes()
        {
            UsuarioViewModel usuario = usuarioRepository.GetUsuario(User.Identity.Name);
            if (usuario == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(usuario);
        }

        [Authorize]
        public ActionResult Edit()
        {
            
            UsuarioSignInViewModel user = usuarioRepository.GetUsuarioSignIn(User.Identity.Name);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(user);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "UsuarioID,NomeUsuario,Senha,ConfirmarSenha,NomeCompleto,Email,Telefone")] UsuarioSignInViewModel usuario)
        {
            UsuarioLoginViewModel login = new UsuarioLoginViewModel()
            {
                Login = usuario.NomeUsuario,
                Senha = usuario.ConfirmarSenha
            };
            if(!usuarioRepository.CheckUsuario(login))
            {
                ModelState.AddModelError("", "Senha Invalida.");
                return View(usuario);
            }
            if (usuarioRepository.UpdateUsuario(usuario))
            {
                FormsAuthentication.SignOut();
                FormsAuthentication.SetAuthCookie(usuario.NomeUsuario, false);
                return RedirectToAction("Detalhes");
            }
            ModelState.AddModelError("", "Login já Cadastrado no Sistema.");
            return View(usuario);
        }

        [Authorize]
        [HttpPost]
        public void AlterarSenha(string OldSenha, string NewSenha, string ConfirmNewSenha)
        {
            //string OldSenha,string NewSenha,string ConfirmNewSenha
            usuarioRepository.ChangePassword(User.Identity.Name, OldSenha, NewSenha, ConfirmNewSenha);
            

        }

        [Authorize]
        public ActionResult Index()
        {
            int usuarioID = usuarioRepository.GetUsuarioID(User.Identity.Name);
            var list = clienteRepository.GetClientes(usuarioID);
            return View(list);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Index(string pesquisa)
        {
            int usuarioID = usuarioRepository.GetUsuarioID(User.Identity.Name);
            var list = clienteRepository.GetClientes(usuarioID);
            list = list.Where(x => StringSearch.StartsWith(x.RazaoSocial,pesquisa));
            int size = list.ToList().Count;
            var list2 = list.ToList();
            if (Request.IsAjaxRequest())
                return PartialView("_Clientes", list);

            return View(list);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ExcluirCliente(int id)
        {
            clienteRepository.RemoveCliente(id);
            int Id = usuarioRepository.GetUsuarioID(User.Identity.Name);
            if (Request.IsAjaxRequest())
                return PartialView("_Clientes",clienteRepository.GetClientes(Id));

            return RedirectToAction("Index");
        }
    }
}

ControleCliente.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Usuario</title>
    <link href="~/Content/all.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand mr-auto" href="@Url.Action("Index","Usuario")">Controle Clientes</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                @if (Request.IsAuthenticated)
                   {
                   using (Html.BeginForm("Index", "Usuario", FormMethod.Post, 
                       new { @class = "form-inline my-2 my-lg-0 ml-auto", id = "navSearch" }))
                   {
                        @Html.TextBox("pesquisa","",new { @class= "form-control mr-sm-2",placeholder="Razão Social"})
                        <button class="btn btn-primary my-2 my-sm-0" type="submit"><i class="fa fa-search mr-1"></i>Buscar</button>
                    }

                }
                <ul class="navbar-nav ml-auto">
                    @if (!Request.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link" href="@Url.Action("Login","Conta")">Logar</a>
                        </li>
                    }

                    @if (Request.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link" href="@Url.Action("Index","Usuario")">Clientes</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navDrop">Olá @User.Identity.Name</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="@Url.Action("Detalhes","Usuario")" class="dropdown-item"><span class="fa fa-user-edit"></span> Meus Dados</a>
                                <a class="dropdown-item" href="@Url.Action("LogOff","Conta")"> <span class="fa fa-sign-out-alt"></span> Sair</a>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>







    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Clientes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>